apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: akcluster
  region: ap-south-1

nodeGroups:
  - name: ng1
    desiredCapacity: 2
    instanceType: t2.micro
    volumeSize: 20
    ssh:
      publicKeyName: eksclust
  - name: ng2
    desiredCapacity: 1
    instanceType: t2.small
    volumeSize: 10
    ssh:
      publicKeyName: eksclust