apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-akcluster
  region: ap-southeast-1

fargateProfiles:
  - name: fatgate-default
    selectors:
      - namespace: kube-system
      - namespace: default
      - namespace: arunkush